Vagrant.configure("2") do |config|
if Vagrant.has_plugin? "vagrant-vbguest"
config.vbguest.no_install = true
config.vbguest.auto_update = false
config.vbguest.no_remote = true
end
config.vm.define :nodo1 do |nodo1|
nodo1.vm.box = "bento/ubuntu-20.04"
nodo1.vm.network :private_network, ip: "192.168.70.10"
nodo1.vm.hostname = "nodo1"
end
config.vm.define :nodo2 do |nodo2|
nodo2.vm.box = "bento/ubuntu-20.04"
nodo2.vm.network :private_network, ip: "192.168.70.11"
nodo2.vm.hostname = "nodo2"
end
config.vm.define :nodo3 do |nodo3|
nodo3.vm.box = "bento/ubuntu-20.04"
nodo3.vm.network :private_network, ip: "192.168.70.12"
nodo3.vm.hostname = "nodo3"
end
config.vm.define :nodo4 do |nodo4|
nodo4.vm.box = "bento/ubuntu-20.04"
nodo4.vm.network :private_network, ip: "192.168.70.13"
nodo4.vm.hostname = "nodo4"
end
config.vm.define :balanceadorm do |balanceadorm|
balanceadorm.vm.box = "bento/ubuntu-20.04"
balanceadorm.vm.network :private_network, ip: "192.168.70.8"
balanceadorm.vm.hostname = "balanceadorm"
end
config.vm.define :clientesql do |clientesql|
clientesql.vm.box = "bento/ubuntu-20.04"
clientesql.vm.network :private_network, ip: "192.168.70.9"
clientesql.vm.hostname = "clientesql"
end
end