Vagrant.configure("2") do |config|
if Vagrant.has_plugin? "vagrant-vbguest"
config.vbguest.no_install = true
config.vbguest.auto_update = false
config.vbguest.no_remote = true
end
#config.vbguest.installer_options = { allow_kernel_upgrade: true }
 config.vm.define :servidor do |servidor|
 servidor.vm.provision "shell", path: "provisionstreama.sh"
 servidor.vm.box = "bento/ubuntu-20.04"
 servidor.vm.network :private_network, ip: "192.168.10.4"
 servidor.vm.hostname = "servidor"

 end
 config.vm.define :firewall do |firewall|
 firewall.vm.provision "shell", path: "provisionfirewall.sh"
 firewall.vm.box = "generic/centos8" 

 firewall.vm.network :private_network, ip: "192.168.10.3"
 firewall.vm.hostname = "firewall"
 end

 
 end
